language: python
dist: trusty
python:
  - "2.7"
notifications: 
  email: false
install: 
  - pip install Cython
  - pip install -r requirements.txt
  - pip install nose
  - pip install codecov
  - touch gurobipy.py
script: "python -m nose pympc --with-coverage --exclude=test_MPCController --exclude=test_MPCHybridController --exclude=test_linear_program --exclude=test_quadratic_program"
after_success:
  - codecov